name: meteorlologist
favicon: null
layout_spectrum: 0.69924
typography_spectrum: 0.87717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#caebfe'
    - '#77b4ea'
    - '#15161b'
    - '#b92000'
    - '#c3a046'
  brandStrength: 0.25
  lightness: 0.36265563243068755
  saturation: 0.6729710381478071
  rhythmicContrast: 0.25
purpose: []
