name: meteorlologist
favicon: null
layout_spectrum: 0.35608001286163926
typography_spectrum: 0.14436932932585478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.36265563243068755
  saturation: 0.6729710381478071
  rhythmicContrast: 0.25
purpose: []
